import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1786163386182 implements MigrationInterface {
    name = 'InitialSchema1786163386182'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE EXTENSION IF NOT EXISTS "uuid-ossp"`);
        await queryRunner.query(`CREATE TABLE "businesses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "name" character varying NOT NULL, "taxId" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_bc1bf63498dd2368ce3dc8686e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."vouchers_status_enum" AS ENUM('active', 'redeemed', 'expired')`);
        await queryRunner.query(`CREATE TABLE "vouchers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "code" character varying NOT NULL, "customerId" uuid, "amount" numeric(14,2) NOT NULL, "balance" numeric(14,2) NOT NULL, "status" "public"."vouchers_status_enum" NOT NULL DEFAULT 'active', "reason" character varying, "expiresAt" date, CONSTRAINT "UQ_efc30b2b9169e05e0e1e19d6dd6" UNIQUE ("code"), CONSTRAINT "PK_ed1b7dd909a696560763acdbc04" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e33dda0ca34b8b72e866b947a5" ON "vouchers"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "code" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "description" character varying, CONSTRAINT "uq_role_business_name" UNIQUE ("businessId", "name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2254391b0628032a713fce697d" ON "roles"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "isSuperAdmin" boolean NOT NULL DEFAULT false, "roleId" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78725ac7117e7526e028014606" ON "users"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "location" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_09b8b9e2811bfd160b328f4a71" ON "warehouses"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "cash_registers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "name" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_c1cc711056395d079d8f041ce34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7086a3477762712ed74010768e" ON "cash_registers"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."cash_sessions_status_enum" AS ENUM('open', 'closed')`);
        await queryRunner.query(`CREATE TABLE "cash_sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "userId" uuid NOT NULL, "warehouseId" uuid, "cashRegisterId" uuid, "openingAmount" numeric(14,2) NOT NULL DEFAULT '0', "countedAmount" numeric(14,2), "expectedAmount" numeric(14,2), "difference" numeric(14,2), "status" "public"."cash_sessions_status_enum" NOT NULL DEFAULT 'open', "openedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "closedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_946ea5ce864b10fb70162708448" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_46873b17300cd1d8719141a8b6" ON "cash_sessions"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."cash_movements_type_enum" AS ENUM('in', 'out')`);
        await queryRunner.query(`CREATE TABLE "cash_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "sessionId" uuid NOT NULL, "type" "public"."cash_movements_type_enum" NOT NULL, "amount" numeric(14,2) NOT NULL, "concept" character varying NOT NULL, "refType" character varying, "refId" uuid, CONSTRAINT "PK_25faead19e1ff74153a01604d37" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_81294ecc660543c080efcd3326" ON "cash_movements"  ("sessionId") `);
        await queryRunner.query(`CREATE TABLE "brands" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30bbb83200bc59d63c2b93b6f6" ON "brands"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."attribute_definitions_type_enum" AS ENUM('text', 'number', 'boolean', 'select')`);
        await queryRunner.query(`CREATE TABLE "attribute_definitions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "type" "public"."attribute_definitions_type_enum" NOT NULL DEFAULT 'text', "unit" character varying, "isVariant" boolean NOT NULL DEFAULT false, "options" jsonb, CONSTRAINT "PK_0430dd4f09c3ff09daa16484676" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac91cbc758b0ba5988a35c631e" ON "attribute_definitions"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "parentId" uuid, CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a018fc1aa37f34fdde4f0a1982" ON "categories"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "category_attributes" ("categoryId" uuid NOT NULL, "attributeDefinitionId" uuid NOT NULL, "required" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_600817b6b6c8c8de08da62e7b4d" PRIMARY KEY ("categoryId", "attributeDefinitionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."credit_notes_type_enum" AS ENUM('partial', 'total')`);
        await queryRunner.query(`CREATE TABLE "credit_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "number" character varying NOT NULL, "saleId" uuid NOT NULL, "customerId" uuid, "type" "public"."credit_notes_type_enum" NOT NULL, "amount" numeric(14,2) NOT NULL, "reason" character varying, "restock" boolean NOT NULL DEFAULT false, "voucherId" uuid, CONSTRAINT "PK_4933888a20b5469e119ad74b9e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_680faacd51d549369626e17381" ON "credit_notes"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."customers_doctype_enum" AS ENUM('CC', 'NIT', 'CE', 'PASSPORT')`);
        await queryRunner.query(`CREATE TYPE "public"."customers_source_enum" AS ENUM('pos', 'ecommerce')`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "docType" "public"."customers_doctype_enum", "docNumber" character varying, "email" character varying, "phone" character varying, "address" character varying, "source" "public"."customers_source_enum" NOT NULL DEFAULT 'pos', "hasAccount" boolean NOT NULL DEFAULT false, "passwordHash" character varying, "defaultPriceListId" uuid, "loyaltyPoints" integer NOT NULL DEFAULT '0', "balance" numeric(14,2) NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_652f05fd67ef9354cb047aae57" ON "customers"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "sku" character varying NOT NULL, "name" character varying NOT NULL, "description" text, "categoryId" uuid, "brandId" uuid, "unit" character varying NOT NULL DEFAULT 'unidad', "tracksInventory" boolean NOT NULL DEFAULT true, "hasVariants" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "uq_product_business_sku" UNIQUE ("businessId", "sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_359bd8406fbfb50e3ea42b5631" ON "products"  ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff56834e735fa78a15d0cf2192" ON "products"  ("categoryId") `);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "productId" uuid NOT NULL, "cost" numeric(14,2) NOT NULL DEFAULT '0', "listPrice" numeric(14,2), "discountPercent" numeric(5,2) NOT NULL DEFAULT '0', "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f515690c571a03400a9876600b" ON "product_variants"  ("productId") `);
        await queryRunner.query(`CREATE TABLE "stock" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "variantId" uuid, "productId" uuid, "warehouseId" uuid NOT NULL, "quantity" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "chk_stock_owner" CHECK (("variantId" IS NOT NULL AND "productId" IS NULL) OR ("variantId" IS NULL AND "productId" IS NOT NULL)), CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6d339d8c94554cdb8c4107218d" ON "stock"  ("variantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e855a71c31948188c2bf78824a" ON "stock"  ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cc5be32db1259f44995d0100a" ON "stock"  ("warehouseId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_stock_product_warehouse" ON "stock"  ("productId", "warehouseId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_stock_variant_warehouse" ON "stock"  ("variantId", "warehouseId") `);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "category" character varying NOT NULL, "description" character varying, "amount" numeric(14,2) NOT NULL, "userId" uuid, "date" date NOT NULL, CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f118b85dd17e066634b2befaad" ON "expenses"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."business_invoicing_settings_provider_enum" AS ENUM('none', 'amovil')`);
        await queryRunner.query(`CREATE TABLE "business_invoicing_settings" ("businessId" uuid NOT NULL, "electronicInvoicingEnabled" boolean NOT NULL DEFAULT false, "provider" "public"."business_invoicing_settings_provider_enum" NOT NULL DEFAULT 'none', "credentials" jsonb, CONSTRAINT "PK_a0fc57f1a2e7db3e6453799906e" PRIMARY KEY ("businessId"))`);
        await queryRunner.query(`CREATE TYPE "public"."sale_electronic_invoices_status_enum" AS ENUM('pending', 'sent', 'accepted', 'rejected', 'error')`);
        await queryRunner.query(`CREATE TABLE "sale_electronic_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "saleId" uuid NOT NULL, "provider" character varying NOT NULL, "externalId" character varying, "status" "public"."sale_electronic_invoices_status_enum" NOT NULL DEFAULT 'pending', "xmlUrl" character varying, "pdfUrl" character varying, "errorMessage" character varying, "attempts" integer NOT NULL DEFAULT '0', CONSTRAINT "UQ_647f74815495e3cc04d87d90963" UNIQUE ("saleId"), CONSTRAINT "PK_cd592e8498eb5459f91d0e6b1aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "loyalty_settings" ("businessId" uuid NOT NULL, "pointsPerAmount" numeric(14,2) NOT NULL DEFAULT '0', "amountUnit" numeric(14,2) NOT NULL DEFAULT '1000', "enabled" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_efa8be359aab71dbd379fbc627d" PRIMARY KEY ("businessId"))`);
        await queryRunner.query(`CREATE TYPE "public"."stock_movements_type_enum" AS ENUM('initial', 'sale', 'sale_void', 'purchase', 'credit_note_restock', 'adjustment_set', 'adjustment_add', 'count')`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "variantId" uuid, "productId" uuid, "warehouseId" uuid NOT NULL, "quantityDelta" numeric(14,2) NOT NULL, "quantityAfter" numeric(14,2) NOT NULL, "type" "public"."stock_movements_type_enum" NOT NULL, "reason" character varying, "refType" character varying, "refId" uuid, "userId" uuid, "date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_847ae48018bbd08f4fbbac5300" ON "stock_movements"  ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d118fa925e343f74b7dfe822e" ON "stock_movements"  ("warehouseId") `);
        await queryRunner.query(`CREATE TABLE "price_lists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "isDefault" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_fd66ee20b065696da25c97fa45a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_518a1324ce1a66bde664925253" ON "price_lists"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "price_list_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "priceListId" uuid NOT NULL, "variantId" uuid, "productId" uuid, "price" numeric(14,2) NOT NULL DEFAULT '0', CONSTRAINT "chk_price_item_owner" CHECK (("variantId" IS NOT NULL AND "productId" IS NULL) OR ("variantId" IS NULL AND "productId" IS NOT NULL)), CONSTRAINT "PK_cdb44449658589feac39de86695" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97f080960141255e54eecb9bdb" ON "price_list_items"  ("priceListId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_price_list_product" ON "price_list_items"  ("priceListId", "productId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_price_list_variant" ON "price_list_items"  ("priceListId", "variantId") `);
        await queryRunner.query(`CREATE TYPE "public"."loyalty_point_transactions_type_enum" AS ENUM('earned', 'redeemed', 'adjustment', 'expired')`);
        await queryRunner.query(`CREATE TABLE "loyalty_point_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "customerId" uuid NOT NULL, "saleId" uuid, "points" integer NOT NULL, "type" "public"."loyalty_point_transactions_type_enum" NOT NULL, "description" character varying, "date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_7c61d857b70bf9f4c4954362a4a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b4f498953327e675a5b4aad822" ON "loyalty_point_transactions"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_method_enum" AS ENUM('cash', 'card', 'transfer', 'voucher', 'credit', 'online_gateway')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "customerId" uuid, "method" "public"."payments_method_enum" NOT NULL, "amount" numeric(14,2) NOT NULL, "userId" uuid NOT NULL, "cashSessionId" uuid, "date" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9628bb768218b756d120c5e545" ON "payments"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."sales_channel_enum" AS ENUM('pos', 'ecommerce')`);
        await queryRunner.query(`CREATE TYPE "public"."sales_status_enum" AS ENUM('confirmed', 'partial', 'paid', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "sales" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "number" character varying NOT NULL, "channel" "public"."sales_channel_enum" NOT NULL DEFAULT 'pos', "customerId" uuid, "priceListId" uuid, "warehouseId" uuid NOT NULL, "userId" uuid NOT NULL, "cashSessionId" uuid, "subtotal" numeric(14,2) NOT NULL DEFAULT '0', "discount" numeric(14,2) NOT NULL DEFAULT '0', "tax" numeric(14,2) NOT NULL DEFAULT '0', "total" numeric(14,2) NOT NULL DEFAULT '0', "paidAmount" numeric(14,2) NOT NULL DEFAULT '0', "status" "public"."sales_status_enum" NOT NULL DEFAULT 'confirmed', "date" TIMESTAMP WITH TIME ZONE NOT NULL, "label" character varying, "voidReason" character varying, "voidedAt" TIMESTAMP WITH TIME ZONE, "voidedBy" uuid, CONSTRAINT "PK_4f0bc990ae81dba46da680895ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d93a36170161fb9969ad3a690f" ON "sales"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "payment_allocations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "paymentId" uuid NOT NULL, "saleId" uuid NOT NULL, "amount" numeric(14,2) NOT NULL, CONSTRAINT "PK_a5c6ff22065ac772620c85f4efb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_68129272bde8768a20d6967a62" ON "payment_allocations"  ("paymentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5eaa1aa5dfc0ea956d547c79c9" ON "payment_allocations"  ("saleId") `);
        await queryRunner.query(`CREATE TABLE "kit_components" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kitProductId" uuid NOT NULL, "componentVariantId" uuid, "componentProductId" uuid, "quantity" numeric(14,2) NOT NULL DEFAULT '1', CONSTRAINT "chk_kit_component_owner" CHECK (("componentVariantId" IS NOT NULL AND "componentProductId" IS NULL) OR ("componentVariantId" IS NULL AND "componentProductId" IS NOT NULL)), CONSTRAINT "PK_34f04573bc149465005a040d299" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_barcodes_type_enum" AS ENUM('ean13', 'upc', 'internal', 'qr')`);
        await queryRunner.query(`CREATE TABLE "product_barcodes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "variantId" uuid, "productId" uuid, "code" character varying NOT NULL, "type" "public"."product_barcodes_type_enum" NOT NULL DEFAULT 'internal', "isPrimary" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_8af65ccf2348282f81fe79c3c82" UNIQUE ("code"), CONSTRAINT "chk_barcode_owner" CHECK (("variantId" IS NOT NULL AND "productId" IS NULL) OR ("variantId" IS NULL AND "productId" IS NOT NULL)), CONSTRAINT "PK_459d7d53aebb732e6c8460247d6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_attribute_values" ("productId" uuid NOT NULL, "attributeDefinitionId" uuid NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_2c0ea1662cb438fd48b37eea911" PRIMARY KEY ("productId", "attributeDefinitionId"))`);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "productId" uuid NOT NULL, "url" character varying NOT NULL, "order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b367708bf720c8dd62fc683316" ON "product_images"  ("productId") `);
        await queryRunner.query(`CREATE TYPE "public"."promotions_type_enum" AS ENUM('percentage', 'fixed_amount', 'buy_x_get_y')`);
        await queryRunner.query(`CREATE TYPE "public"."promotions_scope_enum" AS ENUM('all', 'category', 'product', 'variant')`);
        await queryRunner.query(`CREATE TABLE "promotions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "type" "public"."promotions_type_enum" NOT NULL, "scope" "public"."promotions_scope_enum" NOT NULL DEFAULT 'all', "value" numeric(14,2), "conditions" jsonb, "startDate" TIMESTAMP WITH TIME ZONE, "endDate" TIMESTAMP WITH TIME ZONE, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_380cecbbe3ac11f0e5a7c452c34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b5d71f7c2d94869d17abba67e0" ON "promotions"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."promotion_targets_targettype_enum" AS ENUM('category', 'product', 'variant')`);
        await queryRunner.query(`CREATE TABLE "promotion_targets" ("promotionId" uuid NOT NULL, "targetType" "public"."promotion_targets_targettype_enum" NOT NULL, "targetId" uuid NOT NULL, CONSTRAINT "PK_e1bf68136ce9e175685305c6a9d" PRIMARY KEY ("promotionId", "targetType", "targetId"))`);
        await queryRunner.query(`CREATE TYPE "public"."purchase_invoices_documenttype_enum" AS ENUM('invoice', 'support_document')`);
        await queryRunner.query(`CREATE TABLE "purchase_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "number" character varying NOT NULL, "documentType" "public"."purchase_invoices_documenttype_enum" NOT NULL, "supplierId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "purchaseOrderId" uuid, "supplierDocNumber" character varying, "total" numeric(14,2) NOT NULL DEFAULT '0', "date" date NOT NULL, CONSTRAINT "PK_efa8a22a9bf7685952deba65c30" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_027ed4718d68ccfcbd0237a32c" ON "purchase_invoices"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "purchase_invoice_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "invoiceId" uuid NOT NULL, "variantId" uuid, "productId" uuid, "description" character varying NOT NULL, "quantity" numeric(14,2) NOT NULL, "unitCost" numeric(14,2) NOT NULL, "total" numeric(14,2) NOT NULL, CONSTRAINT "chk_pi_line_owner" CHECK (("variantId" IS NOT NULL AND "productId" IS NULL) OR ("variantId" IS NULL AND "productId" IS NOT NULL)), CONSTRAINT "PK_0052805e432dca6a57d51f66f7a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff420c61a0a388e44e711d0a3b" ON "purchase_invoice_lines"  ("invoiceId") `);
        await queryRunner.query(`CREATE TABLE "variant_attribute_values" ("variantId" uuid NOT NULL, "attributeDefinitionId" uuid NOT NULL, "value" character varying NOT NULL, CONSTRAINT "PK_278f1e3791ced66b75995bb0d9e" PRIMARY KEY ("variantId", "attributeDefinitionId"))`);
        await queryRunner.query(`CREATE TYPE "public"."quotes_status_enum" AS ENUM('draft', 'sent', 'approved', 'rejected', 'converted')`);
        await queryRunner.query(`CREATE TABLE "quotes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "number" character varying NOT NULL, "customerId" uuid, "status" "public"."quotes_status_enum" NOT NULL DEFAULT 'draft', "validUntil" date, "subtotal" numeric(14,2) NOT NULL DEFAULT '0', "discount" numeric(14,2) NOT NULL DEFAULT '0', "total" numeric(14,2) NOT NULL DEFAULT '0', "saleId" uuid, CONSTRAINT "PK_99a0e8bcbcd8719d3a41f23c263" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1b8e9ffc45eb9c2bfd3209024" ON "quotes"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "quote_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "quoteId" uuid NOT NULL, "variantId" uuid, "productId" uuid, "description" character varying NOT NULL, "quantity" numeric(14,2) NOT NULL, "unitPrice" numeric(14,2) NOT NULL, "discount" numeric(14,2) NOT NULL DEFAULT '0', "total" numeric(14,2) NOT NULL, CONSTRAINT "chk_quote_line_owner" CHECK (("variantId" IS NOT NULL AND "productId" IS NULL) OR ("variantId" IS NULL AND "productId" IS NOT NULL)), CONSTRAINT "PK_4589e13e3a55c06472a7dee6e31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b37b2b6c6c350a5439d90e092d" ON "quote_lines"  ("quoteId") `);
        await queryRunner.query(`CREATE TABLE "debit_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "number" character varying NOT NULL, "supplierId" uuid NOT NULL, "purchaseInvoiceId" uuid, "amount" numeric(14,2) NOT NULL, "reason" character varying, "date" date NOT NULL, CONSTRAINT "PK_e1f73e65add1542776ce7087fae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8beb53f3e37d48698a0d3fe6bd" ON "debit_notes"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."recurring_invoices_frequency_enum" AS ENUM('weekly', 'monthly')`);
        await queryRunner.query(`CREATE TABLE "recurring_invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "customerId" uuid, "warehouseId" uuid NOT NULL, "frequency" "public"."recurring_invoices_frequency_enum" NOT NULL, "nextRun" date NOT NULL, "active" boolean NOT NULL DEFAULT true, "lines" jsonb NOT NULL DEFAULT '[]', CONSTRAINT "PK_8a156fda29720c5fc4f86c89081" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c295a2784e90c8fcf1e8d0df8e" ON "recurring_invoices"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."purchase_orders_status_enum" AS ENUM('draft', 'sent', 'received', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "number" character varying NOT NULL, "supplierId" uuid NOT NULL, "warehouseId" uuid NOT NULL, "status" "public"."purchase_orders_status_enum" NOT NULL DEFAULT 'draft', "total" numeric(14,2) NOT NULL DEFAULT '0', "date" date NOT NULL, CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_526a058859501c706e473d1835" ON "purchase_orders"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "purchase_order_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "orderId" uuid NOT NULL, "variantId" uuid, "productId" uuid, "description" character varying NOT NULL, "quantity" numeric(14,2) NOT NULL, "unitCost" numeric(14,2) NOT NULL, "total" numeric(14,2) NOT NULL, CONSTRAINT "chk_po_line_owner" CHECK (("variantId" IS NOT NULL AND "productId" IS NULL) OR ("variantId" IS NULL AND "productId" IS NOT NULL)), CONSTRAINT "PK_34a2082d2abb10c5d8713bc19b8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05209d4e9633b8725cdc1b1097" ON "purchase_order_lines"  ("orderId") `);
        await queryRunner.query(`CREATE TABLE "task_columns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_ff743949cd48d0dc50d1c0fd65b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77ed1743c88ec6a61cc200af6b" ON "task_columns"  ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."suppliers_doctype_enum" AS ENUM('CC', 'NIT', 'CE', 'PASSPORT')`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "name" character varying NOT NULL, "docType" "public"."suppliers_doctype_enum", "docNumber" character varying, "email" character varying, "phone" character varying, "address" character varying, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c17125a2cc40433d03130fe041" ON "suppliers"  ("businessId") `);
        await queryRunner.query(`CREATE TABLE "sale_lines" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "saleId" uuid NOT NULL, "variantId" uuid, "productId" uuid, "description" character varying NOT NULL, "quantity" numeric(14,2) NOT NULL, "unitPrice" numeric(14,2) NOT NULL, "discount" numeric(14,2) NOT NULL DEFAULT '0', "promotionId" uuid, "tax" numeric(14,2) NOT NULL DEFAULT '0', "total" numeric(14,2) NOT NULL, CONSTRAINT "chk_sale_line_owner" CHECK (("variantId" IS NOT NULL AND "productId" IS NULL) OR ("variantId" IS NULL AND "productId" IS NOT NULL)), CONSTRAINT "PK_d3e4396511029d8a97d9e946fb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b9839a37392398a402bc130e1a" ON "sale_lines"  ("saleId") `);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "businessId" uuid NOT NULL, "title" character varying NOT NULL, "description" character varying, "columnId" uuid NOT NULL, "assigneeId" uuid, "order" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b1699838e5cfdf023523a0d73d" ON "tasks"  ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_0ecfe75e5bd731e00e634d70e5" ON "tasks"  ("columnId") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("rolesId" uuid NOT NULL, "permissionsId" uuid NOT NULL, CONSTRAINT "PK_7931614007a93423204b4b73240" PRIMARY KEY ("rolesId", "permissionsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0cb93c5877d37e954e2aa59e52" ON "role_permissions"  ("rolesId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d422dabc78ff74a8dab6583da0" ON "role_permissions"  ("permissionsId") `);
        await queryRunner.query(`ALTER TABLE "vouchers" ADD CONSTRAINT "FK_e33dda0ca34b8b72e866b947a5f" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_2254391b0628032a713fce697d8" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_78725ac7117e7526e028014606b" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouses" ADD CONSTRAINT "FK_09b8b9e2811bfd160b328f4a71d" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_registers" ADD CONSTRAINT "FK_7086a3477762712ed74010768e9" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_registers" ADD CONSTRAINT "FK_6a1cd0ccb99f5e0799d6b402fc9" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_46873b17300cd1d8719141a8b63" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_6a3b9a595837239c582e9cffc3d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_a0666bdfc9f549fab14858a843b" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" ADD CONSTRAINT "FK_e61a93525d6ec464a20b7e2fff5" FOREIGN KEY ("cashRegisterId") REFERENCES "cash_registers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cash_movements" ADD CONSTRAINT "FK_81294ecc660543c080efcd33265" FOREIGN KEY ("sessionId") REFERENCES "cash_sessions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "brands" ADD CONSTRAINT "FK_30bbb83200bc59d63c2b93b6f6e" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attribute_definitions" ADD CONSTRAINT "FK_ac91cbc758b0ba5988a35c631e8" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_a018fc1aa37f34fdde4f0a1982c" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_attributes" ADD CONSTRAINT "FK_38209e8493459f8b98aa107be2b" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category_attributes" ADD CONSTRAINT "FK_edf58ec4a86bd8aa346a560f9a6" FOREIGN KEY ("attributeDefinitionId") REFERENCES "attribute_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "credit_notes" ADD CONSTRAINT "FK_680faacd51d549369626e17381f" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customers" ADD CONSTRAINT "FK_652f05fd67ef9354cb047aae572" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df" FOREIGN KEY ("brandId") REFERENCES "brands"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_6d339d8c94554cdb8c4107218d9" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_e855a71c31948188c2bf78824a5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock" ADD CONSTRAINT "FK_2cc5be32db1259f44995d0100aa" FOREIGN KEY ("warehouseId") REFERENCES "warehouses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_f118b85dd17e066634b2befaad2" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_lists" ADD CONSTRAINT "FK_518a1324ce1a66bde6649252539" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_list_items" ADD CONSTRAINT "FK_97f080960141255e54eecb9bdbd" FOREIGN KEY ("priceListId") REFERENCES "price_lists"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_list_items" ADD CONSTRAINT "FK_62e2bd922d11fc8204172d6789c" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_list_items" ADD CONSTRAINT "FK_f4460b6ee8677a87247e107e2b7" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loyalty_point_transactions" ADD CONSTRAINT "FK_b4f498953327e675a5b4aad8223" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_9628bb768218b756d120c5e5454" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sales" ADD CONSTRAINT "FK_d93a36170161fb9969ad3a690fd" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_68129272bde8768a20d6967a62c" FOREIGN KEY ("paymentId") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" ADD CONSTRAINT "FK_5eaa1aa5dfc0ea956d547c79c9e" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kit_components" ADD CONSTRAINT "FK_70236412133547438bd2390df03" FOREIGN KEY ("kitProductId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kit_components" ADD CONSTRAINT "FK_c8d1db0e32552d6482de32d5a58" FOREIGN KEY ("componentVariantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "kit_components" ADD CONSTRAINT "FK_2ee9e2af531aeb09df5af96fef9" FOREIGN KEY ("componentProductId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_barcodes" ADD CONSTRAINT "FK_80bff17375afe2eedd36257c083" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_barcodes" ADD CONSTRAINT "FK_258b80cebb40fb6ac0f54126959" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" ADD CONSTRAINT "FK_6f387b01fd9800591fa425dd203" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" ADD CONSTRAINT "FK_6d5587f03f3bb31263dd34f1d57" FOREIGN KEY ("attributeDefinitionId") REFERENCES "attribute_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_b367708bf720c8dd62fc6833161" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotions" ADD CONSTRAINT "FK_b5d71f7c2d94869d17abba67e08" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "promotion_targets" ADD CONSTRAINT "FK_68a3b5100bbc9fcbc8da6c90be7" FOREIGN KEY ("promotionId") REFERENCES "promotions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_invoices" ADD CONSTRAINT "FK_027ed4718d68ccfcbd0237a32c9" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_invoice_lines" ADD CONSTRAINT "FK_ff420c61a0a388e44e711d0a3b1" FOREIGN KEY ("invoiceId") REFERENCES "purchase_invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_invoice_lines" ADD CONSTRAINT "FK_afd882909d28dae4f05008fb048" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_invoice_lines" ADD CONSTRAINT "FK_edc4abe3c7b64bc704e6bb261dc" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" ADD CONSTRAINT "FK_7c0b50714d82aca370fe83658e2" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" ADD CONSTRAINT "FK_09d0838d716add8a270dd83afef" FOREIGN KEY ("attributeDefinitionId") REFERENCES "attribute_definitions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quotes" ADD CONSTRAINT "FK_b1b8e9ffc45eb9c2bfd32090242" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_lines" ADD CONSTRAINT "FK_b37b2b6c6c350a5439d90e092da" FOREIGN KEY ("quoteId") REFERENCES "quotes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_lines" ADD CONSTRAINT "FK_ae905d3a5c1c1ed25fcc860d09f" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "quote_lines" ADD CONSTRAINT "FK_fdafcdd6e0e670c3417856ac766" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "debit_notes" ADD CONSTRAINT "FK_8beb53f3e37d48698a0d3fe6bd3" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "recurring_invoices" ADD CONSTRAINT "FK_c295a2784e90c8fcf1e8d0df8ec" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" ADD CONSTRAINT "FK_526a058859501c706e473d18352" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_05209d4e9633b8725cdc1b1097e" FOREIGN KEY ("orderId") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_0725cd52f439e7e6143b9ad3e89" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" ADD CONSTRAINT "FK_d96db03df749514dd9b5f36ad2b" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_columns" ADD CONSTRAINT "FK_77ed1743c88ec6a61cc200af6b0" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "suppliers" ADD CONSTRAINT "FK_c17125a2cc40433d03130fe0410" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "FK_b9839a37392398a402bc130e1a5" FOREIGN KEY ("saleId") REFERENCES "sales"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "FK_e66d6844db6460e1757430b5e18" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sale_lines" ADD CONSTRAINT "FK_5bb181f3e04bb1f0f14c16d9c1f" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_b1699838e5cfdf023523a0d73d0" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_0ecfe75e5bd731e00e634d70e5f" FOREIGN KEY ("columnId") REFERENCES "task_columns"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3" FOREIGN KEY ("assigneeId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c" FOREIGN KEY ("rolesId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_d422dabc78ff74a8dab6583da02" FOREIGN KEY ("permissionsId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_d422dabc78ff74a8dab6583da02"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_0cb93c5877d37e954e2aa59e52c"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9a16d2c86252529f622fa53f1e3"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_0ecfe75e5bd731e00e634d70e5f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_b1699838e5cfdf023523a0d73d0"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "FK_5bb181f3e04bb1f0f14c16d9c1f"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "FK_e66d6844db6460e1757430b5e18"`);
        await queryRunner.query(`ALTER TABLE "sale_lines" DROP CONSTRAINT "FK_b9839a37392398a402bc130e1a5"`);
        await queryRunner.query(`ALTER TABLE "suppliers" DROP CONSTRAINT "FK_c17125a2cc40433d03130fe0410"`);
        await queryRunner.query(`ALTER TABLE "task_columns" DROP CONSTRAINT "FK_77ed1743c88ec6a61cc200af6b0"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_d96db03df749514dd9b5f36ad2b"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_0725cd52f439e7e6143b9ad3e89"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_lines" DROP CONSTRAINT "FK_05209d4e9633b8725cdc1b1097e"`);
        await queryRunner.query(`ALTER TABLE "purchase_orders" DROP CONSTRAINT "FK_526a058859501c706e473d18352"`);
        await queryRunner.query(`ALTER TABLE "recurring_invoices" DROP CONSTRAINT "FK_c295a2784e90c8fcf1e8d0df8ec"`);
        await queryRunner.query(`ALTER TABLE "debit_notes" DROP CONSTRAINT "FK_8beb53f3e37d48698a0d3fe6bd3"`);
        await queryRunner.query(`ALTER TABLE "quote_lines" DROP CONSTRAINT "FK_fdafcdd6e0e670c3417856ac766"`);
        await queryRunner.query(`ALTER TABLE "quote_lines" DROP CONSTRAINT "FK_ae905d3a5c1c1ed25fcc860d09f"`);
        await queryRunner.query(`ALTER TABLE "quote_lines" DROP CONSTRAINT "FK_b37b2b6c6c350a5439d90e092da"`);
        await queryRunner.query(`ALTER TABLE "quotes" DROP CONSTRAINT "FK_b1b8e9ffc45eb9c2bfd32090242"`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" DROP CONSTRAINT "FK_09d0838d716add8a270dd83afef"`);
        await queryRunner.query(`ALTER TABLE "variant_attribute_values" DROP CONSTRAINT "FK_7c0b50714d82aca370fe83658e2"`);
        await queryRunner.query(`ALTER TABLE "purchase_invoice_lines" DROP CONSTRAINT "FK_edc4abe3c7b64bc704e6bb261dc"`);
        await queryRunner.query(`ALTER TABLE "purchase_invoice_lines" DROP CONSTRAINT "FK_afd882909d28dae4f05008fb048"`);
        await queryRunner.query(`ALTER TABLE "purchase_invoice_lines" DROP CONSTRAINT "FK_ff420c61a0a388e44e711d0a3b1"`);
        await queryRunner.query(`ALTER TABLE "purchase_invoices" DROP CONSTRAINT "FK_027ed4718d68ccfcbd0237a32c9"`);
        await queryRunner.query(`ALTER TABLE "promotion_targets" DROP CONSTRAINT "FK_68a3b5100bbc9fcbc8da6c90be7"`);
        await queryRunner.query(`ALTER TABLE "promotions" DROP CONSTRAINT "FK_b5d71f7c2d94869d17abba67e08"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_b367708bf720c8dd62fc6833161"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" DROP CONSTRAINT "FK_6d5587f03f3bb31263dd34f1d57"`);
        await queryRunner.query(`ALTER TABLE "product_attribute_values" DROP CONSTRAINT "FK_6f387b01fd9800591fa425dd203"`);
        await queryRunner.query(`ALTER TABLE "product_barcodes" DROP CONSTRAINT "FK_258b80cebb40fb6ac0f54126959"`);
        await queryRunner.query(`ALTER TABLE "product_barcodes" DROP CONSTRAINT "FK_80bff17375afe2eedd36257c083"`);
        await queryRunner.query(`ALTER TABLE "kit_components" DROP CONSTRAINT "FK_2ee9e2af531aeb09df5af96fef9"`);
        await queryRunner.query(`ALTER TABLE "kit_components" DROP CONSTRAINT "FK_c8d1db0e32552d6482de32d5a58"`);
        await queryRunner.query(`ALTER TABLE "kit_components" DROP CONSTRAINT "FK_70236412133547438bd2390df03"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_5eaa1aa5dfc0ea956d547c79c9e"`);
        await queryRunner.query(`ALTER TABLE "payment_allocations" DROP CONSTRAINT "FK_68129272bde8768a20d6967a62c"`);
        await queryRunner.query(`ALTER TABLE "sales" DROP CONSTRAINT "FK_d93a36170161fb9969ad3a690fd"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_9628bb768218b756d120c5e5454"`);
        await queryRunner.query(`ALTER TABLE "loyalty_point_transactions" DROP CONSTRAINT "FK_b4f498953327e675a5b4aad8223"`);
        await queryRunner.query(`ALTER TABLE "price_list_items" DROP CONSTRAINT "FK_f4460b6ee8677a87247e107e2b7"`);
        await queryRunner.query(`ALTER TABLE "price_list_items" DROP CONSTRAINT "FK_62e2bd922d11fc8204172d6789c"`);
        await queryRunner.query(`ALTER TABLE "price_list_items" DROP CONSTRAINT "FK_97f080960141255e54eecb9bdbd"`);
        await queryRunner.query(`ALTER TABLE "price_lists" DROP CONSTRAINT "FK_518a1324ce1a66bde6649252539"`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_f118b85dd17e066634b2befaad2"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_2cc5be32db1259f44995d0100aa"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_e855a71c31948188c2bf78824a5"`);
        await queryRunner.query(`ALTER TABLE "stock" DROP CONSTRAINT "FK_6d339d8c94554cdb8c4107218d9"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ea86d0c514c4ecbb5694cbf57df"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f"`);
        await queryRunner.query(`ALTER TABLE "customers" DROP CONSTRAINT "FK_652f05fd67ef9354cb047aae572"`);
        await queryRunner.query(`ALTER TABLE "credit_notes" DROP CONSTRAINT "FK_680faacd51d549369626e17381f"`);
        await queryRunner.query(`ALTER TABLE "category_attributes" DROP CONSTRAINT "FK_edf58ec4a86bd8aa346a560f9a6"`);
        await queryRunner.query(`ALTER TABLE "category_attributes" DROP CONSTRAINT "FK_38209e8493459f8b98aa107be2b"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_a018fc1aa37f34fdde4f0a1982c"`);
        await queryRunner.query(`ALTER TABLE "attribute_definitions" DROP CONSTRAINT "FK_ac91cbc758b0ba5988a35c631e8"`);
        await queryRunner.query(`ALTER TABLE "brands" DROP CONSTRAINT "FK_30bbb83200bc59d63c2b93b6f6e"`);
        await queryRunner.query(`ALTER TABLE "cash_movements" DROP CONSTRAINT "FK_81294ecc660543c080efcd33265"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_e61a93525d6ec464a20b7e2fff5"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_a0666bdfc9f549fab14858a843b"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_6a3b9a595837239c582e9cffc3d"`);
        await queryRunner.query(`ALTER TABLE "cash_sessions" DROP CONSTRAINT "FK_46873b17300cd1d8719141a8b63"`);
        await queryRunner.query(`ALTER TABLE "cash_registers" DROP CONSTRAINT "FK_6a1cd0ccb99f5e0799d6b402fc9"`);
        await queryRunner.query(`ALTER TABLE "cash_registers" DROP CONSTRAINT "FK_7086a3477762712ed74010768e9"`);
        await queryRunner.query(`ALTER TABLE "warehouses" DROP CONSTRAINT "FK_09b8b9e2811bfd160b328f4a71d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_78725ac7117e7526e028014606b"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_2254391b0628032a713fce697d8"`);
        await queryRunner.query(`ALTER TABLE "vouchers" DROP CONSTRAINT "FK_e33dda0ca34b8b72e866b947a5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d422dabc78ff74a8dab6583da0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cb93c5877d37e954e2aa59e52"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0ecfe75e5bd731e00e634d70e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1699838e5cfdf023523a0d73d"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b9839a37392398a402bc130e1a"`);
        await queryRunner.query(`DROP TABLE "sale_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c17125a2cc40433d03130fe041"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TYPE "public"."suppliers_doctype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ed1743c88ec6a61cc200af6b"`);
        await queryRunner.query(`DROP TABLE "task_columns"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05209d4e9633b8725cdc1b1097"`);
        await queryRunner.query(`DROP TABLE "purchase_order_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_526a058859501c706e473d1835"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c295a2784e90c8fcf1e8d0df8e"`);
        await queryRunner.query(`DROP TABLE "recurring_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."recurring_invoices_frequency_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8beb53f3e37d48698a0d3fe6bd"`);
        await queryRunner.query(`DROP TABLE "debit_notes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b37b2b6c6c350a5439d90e092d"`);
        await queryRunner.query(`DROP TABLE "quote_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b1b8e9ffc45eb9c2bfd3209024"`);
        await queryRunner.query(`DROP TABLE "quotes"`);
        await queryRunner.query(`DROP TYPE "public"."quotes_status_enum"`);
        await queryRunner.query(`DROP TABLE "variant_attribute_values"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff420c61a0a388e44e711d0a3b"`);
        await queryRunner.query(`DROP TABLE "purchase_invoice_lines"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_027ed4718d68ccfcbd0237a32c"`);
        await queryRunner.query(`DROP TABLE "purchase_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."purchase_invoices_documenttype_enum"`);
        await queryRunner.query(`DROP TABLE "promotion_targets"`);
        await queryRunner.query(`DROP TYPE "public"."promotion_targets_targettype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b5d71f7c2d94869d17abba67e0"`);
        await queryRunner.query(`DROP TABLE "promotions"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_scope_enum"`);
        await queryRunner.query(`DROP TYPE "public"."promotions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b367708bf720c8dd62fc683316"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP TABLE "product_attribute_values"`);
        await queryRunner.query(`DROP TABLE "product_barcodes"`);
        await queryRunner.query(`DROP TYPE "public"."product_barcodes_type_enum"`);
        await queryRunner.query(`DROP TABLE "kit_components"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5eaa1aa5dfc0ea956d547c79c9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68129272bde8768a20d6967a62"`);
        await queryRunner.query(`DROP TABLE "payment_allocations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93a36170161fb9969ad3a690f"`);
        await queryRunner.query(`DROP TABLE "sales"`);
        await queryRunner.query(`DROP TYPE "public"."sales_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."sales_channel_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9628bb768218b756d120c5e545"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4f498953327e675a5b4aad822"`);
        await queryRunner.query(`DROP TABLE "loyalty_point_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."loyalty_point_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_price_list_variant"`);
        await queryRunner.query(`DROP INDEX "public"."uq_price_list_product"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97f080960141255e54eecb9bdb"`);
        await queryRunner.query(`DROP TABLE "price_list_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_518a1324ce1a66bde664925253"`);
        await queryRunner.query(`DROP TABLE "price_lists"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d118fa925e343f74b7dfe822e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_847ae48018bbd08f4fbbac5300"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TYPE "public"."stock_movements_type_enum"`);
        await queryRunner.query(`DROP TABLE "loyalty_settings"`);
        await queryRunner.query(`DROP TABLE "sale_electronic_invoices"`);
        await queryRunner.query(`DROP TYPE "public"."sale_electronic_invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "business_invoicing_settings"`);
        await queryRunner.query(`DROP TYPE "public"."business_invoicing_settings_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f118b85dd17e066634b2befaad"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP INDEX "public"."uq_stock_variant_warehouse"`);
        await queryRunner.query(`DROP INDEX "public"."uq_stock_product_warehouse"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cc5be32db1259f44995d0100a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e855a71c31948188c2bf78824a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d339d8c94554cdb8c4107218d"`);
        await queryRunner.query(`DROP TABLE "stock"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f515690c571a03400a9876600b"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff56834e735fa78a15d0cf2192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_359bd8406fbfb50e3ea42b5631"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_652f05fd67ef9354cb047aae57"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TYPE "public"."customers_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."customers_doctype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_680faacd51d549369626e17381"`);
        await queryRunner.query(`DROP TABLE "credit_notes"`);
        await queryRunner.query(`DROP TYPE "public"."credit_notes_type_enum"`);
        await queryRunner.query(`DROP TABLE "category_attributes"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a018fc1aa37f34fdde4f0a1982"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac91cbc758b0ba5988a35c631e"`);
        await queryRunner.query(`DROP TABLE "attribute_definitions"`);
        await queryRunner.query(`DROP TYPE "public"."attribute_definitions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30bbb83200bc59d63c2b93b6f6"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_81294ecc660543c080efcd3326"`);
        await queryRunner.query(`DROP TABLE "cash_movements"`);
        await queryRunner.query(`DROP TYPE "public"."cash_movements_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46873b17300cd1d8719141a8b6"`);
        await queryRunner.query(`DROP TABLE "cash_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."cash_sessions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7086a3477762712ed74010768e"`);
        await queryRunner.query(`DROP TABLE "cash_registers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_09b8b9e2811bfd160b328f4a71"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78725ac7117e7526e028014606"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2254391b0628032a713fce697d"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e33dda0ca34b8b72e866b947a5"`);
        await queryRunner.query(`DROP TABLE "vouchers"`);
        await queryRunner.query(`DROP TYPE "public"."vouchers_status_enum"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
    }

}
