export const BASE_PERMISSIONS = [
  'users.manage',
  'roles.manage',
  'catalog.read',
  'catalog.write',
  'inventory.read',
  'inventory.write',
  'pricing.read',
  'pricing.write',
  'sales.read',
  'sales.write',
  'cash.manage',
  'payments.write',
  'customers.read',
  'customers.write',
  'suppliers.read',
  'suppliers.write',
  'purchases.read',
  'purchases.write',
  'quotes.read',
  'quotes.write',
  'vouchers.manage',
  'credit_notes.write',
  'recurring.manage',
  'loyalty.manage',
  'invoicing.manage',
  'reports.read',
  'tasks.manage',
] as const;

export type BasePermissionCode = (typeof BASE_PERMISSIONS)[number];
